"use client";

import { useEffect, useMemo, useState } from "react";

const FEATURES = ["possession_share", "avg_pass_length", "forward_pass_ratio", "long_pass_ratio", "avg_action_height", "width_dispersion"];
const LABELS: Record<string, string> = { possession_share: "Possession", avg_pass_length: "Pass length", forward_pass_ratio: "Forward passes", long_pass_ratio: "Long passes", avg_action_height: "Defensive height", width_dispersion: "Width" };
type Signature = Record<string, number | string>;
type Similar = { team: string; similarity: number; reasons?: string[] };
type Profile = { id: string; team: string; competition: string; season: string; signature: Signature; zones: { length: number; width: number; value: number }[]; similar: Similar[]; archetype?: string; archetype_reason?: string; data_quality?: { matches_played: number; label: string } };
type Source = { competition: string; season: string };
type Dataset = { sources?: Source[]; teams: Profile[] };
const metric = (signature: Signature, key: string) => Number(signature[`${key}_mean`] ?? signature[key] ?? 0);
const sourceKey = (source: Source) => `${source.competition}|${source.season}`;
const percent = (value: number) => `${Math.round(value * 100)}%`;

function Radar({ left, right }: { left: Profile; right?: Profile }) {
  const values = (profile: Profile) => FEATURES.map((key) => metric(profile.signature, key));
  const normalise = (raw: number[]) => raw.map((value, index) => value / Math.max(...[...values(left), ...(right ? values(right) : [])].map((row) => Math.abs(row)), .001));
  const polygon = (points: number[]) => points.map((value, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / FEATURES.length; return `${50 + Math.cos(angle) * value * 39},${50 + Math.sin(angle) * value * 39}`; }).join(" ");
  return <div className="radar-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="Tactical radar chart">{[.25, .5, .75, 1].map((radius) => <circle key={radius} cx="50" cy="50" r={39 * radius} fill="none" stroke="rgba(255,255,255,.12)" />)}{FEATURES.map((feature, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / FEATURES.length; return <text key={feature} x={50 + Math.cos(angle) * 48} y={51 + Math.sin(angle) * 48} textAnchor="middle">{LABELS[feature]}</text>; })}<polygon points={polygon(normalise(values(left)))} className="radar-a" />{right && <polygon points={polygon(normalise(values(right)))} className="radar-b" />}</svg><div className="legend"><span className="dot a" />{left.team}{right && <><span className="dot b" />{right.team}</>}</div></div>;
}

function Pitch({ zones }: { zones: Profile["zones"] }) { const max = Math.max(...zones.map((zone) => zone.value), .001); return <div className="pitch" aria-label="Territorial action distribution">{zones.map((zone) => <div key={`${zone.length}-${zone.width}`} className="zone" style={{ opacity: .13 + .87 * zone.value / max }} title={`${(zone.value * 100).toFixed(1)}% action share`} />)}</div>; }

function InsightCards({ profile, peers }: { profile: Profile; peers: Profile[] }) {
  const cards = [["Possession", "possession_share", percent(metric(profile.signature, "possession_share"))], ["Pass length", "avg_pass_length", `${metric(profile.signature, "avg_pass_length").toFixed(1)} m`], ["Forward intent", "forward_pass_ratio", percent(metric(profile.signature, "forward_pass_ratio"))], ["Defensive height", "avg_action_height", percent(metric(profile.signature, "avg_action_height"))]];
  return <section className="insights" aria-label="Key tactical metrics">{cards.map(([label, key, value]) => { const current = metric(profile.signature, key); const rank = peers.length > 1 ? Math.round(100 * peers.filter((item) => metric(item.signature, key) <= current).length / peers.length) : 0; return <article key={key}><span>{label}</span><strong>{value}</strong><small>{peers.length > 1 ? `${rank}th percentile in this source` : "More teams unlock rankings"}</small></article>; })}</section>;
}

function ComparisonTable({ left, right }: { left: Profile; right: Profile }) { return <section className="comparison panel"><span className="eyebrow">Tactical difference</span><h2>{left.team} vs {right.team}</h2>{FEATURES.map((key) => { const a = metric(left.signature, key); const b = metric(right.signature, key); const delta = a - b; const unit = key === "avg_pass_length" ? "m" : "%"; const display = key === "avg_pass_length" ? Math.abs(delta).toFixed(1) : Math.round(Math.abs(delta) * 100); return <div className="metric-row" key={key}><span>{LABELS[key]}</span><strong className={delta >= 0 ? "advantage-a" : "advantage-b"}>{delta === 0 ? "Even" : `${delta > 0 ? left.team : right.team} +${display}${unit}`}</strong></div>; })}</section>; }

export function TacticalExplorer() {
  const [dataset, setDataset] = useState<Dataset | null>(null); const [source, setSource] = useState(""); const [selected, setSelected] = useState(""); const [comparison, setComparison] = useState(""); const [crossSource, setCrossSource] = useState(false); const [shareStatus, setShareStatus] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/data/tactical.json").then((response) => response.ok ? response.json() : Promise.reject()).then((payload: Dataset) => { const teams = payload.teams.map((item) => { const competition = item.competition ?? "Champions League"; const season = item.season ?? "2015"; return { ...item, competition, season, id: item.id ?? `${competition}|${season}|${item.team}` }; }); const sources = payload.sources?.length ? payload.sources : [...new Map(teams.map((item) => [sourceKey(item), { competition: item.competition, season: item.season }])).values()]; const params = new URLSearchParams(window.location.search); const requestedSource = params.get("dataset"); const validSource = sources.some((item) => sourceKey(item) === requestedSource) ? requestedSource! : sourceKey(sources[0]); setDataset({ ...payload, teams, sources }); setSource(validSource); setSelected(params.get("team") ?? ""); setComparison(params.get("compare") ?? ""); }).catch(() => setError("No deployable tactical dataset yet. Run scripts/build_explorer_dataset.py.")); }, []);
  const sources = useMemo(() => dataset?.sources?.length ? dataset.sources : [], [dataset]); const profiles = useMemo(() => dataset?.teams.filter((item) => sourceKey(item) === source) ?? [], [dataset, source]); const comparisonOptions = crossSource ? dataset?.teams ?? [] : profiles;
  useEffect(() => { if (!profiles.some((item) => item.id === selected)) setSelected(profiles[0]?.id ?? ""); }, [profiles, selected]);
  const profile = profiles.find((item) => item.id === selected) ?? null; const comparisonProfile = comparisonOptions.find((item) => item.id === comparison) ?? null; const alternatives = comparisonOptions.filter((item) => item.id !== selected);
  useEffect(() => { if (!selected) return; const params = new URLSearchParams(); params.set("dataset", source); params.set("team", selected); if (comparison) params.set("compare", comparison); window.history.replaceState(null, "", `${window.location.pathname}?${params.toString()}`); }, [source, selected, comparison]);
  const copyShare = async () => { await navigator.clipboard.writeText(window.location.href); setShareStatus("Link copied"); window.setTimeout(() => setShareStatus(""), 1800); };
  return <><section className="hero"><div><span className="eyebrow">Football style intelligence</span><h1>Every team leaves a<br /><em>tactical fingerprint.</em></h1><p>Explore how teams occupy space, progress the ball, and defend—without reducing football to scorelines.</p></div><div className="hero-stat"><span>{profiles.length || "—"}</span><small>team profiles<br />in this source</small></div></section>
    <section className="controls"><label>Dataset<select value={source} onChange={(event) => setSource(event.target.value)}>{sources.map((item) => <option key={sourceKey(item)} value={sourceKey(item)}>{item.competition} {item.season}</option>)}</select></label><label>Team<select value={selected} onChange={(event) => setSelected(event.target.value)}>{profiles.map((item) => <option key={item.id} value={item.id}>{item.team}</option>)}</select></label><label>Compare with<select value={comparison} onChange={(event) => setComparison(event.target.value)}><option value="">No comparison</option>{alternatives.map((item) => <option key={item.id} value={item.id}>{crossSource ? `${item.team} · ${item.competition}` : item.team}</option>)}</select></label><label className="toggle"><input type="checkbox" checked={crossSource} onChange={(event) => setCrossSource(event.target.checked)} />Cross-source</label><button className="share" onClick={copyShare}>{shareStatus || "Share analysis"}</button></section>
    {error && <p className="notice">{error}</p>}{profile && <><div className="profile-meta"><span>{profile.data_quality?.label ?? "Derived profile"}</span><span>{profile.data_quality?.matches_played ?? "—"} matches analysed</span><span>{profile.archetype ?? "Balanced system"}</span></div><InsightCards profile={profile} peers={profiles} /><section className="grid"><div className="panel profile"><div><span className="eyebrow">{profile.competition} · {profile.season}</span><h2>{profile.team} DNA</h2></div><Radar left={profile} right={comparisonProfile ?? undefined} /></div><div className="panel"><span className="eyebrow">Territorial footprint</span><h2>Where actions happen</h2><Pitch zones={profile.zones} /></div><div className="style-card"><span className="eyebrow">Tactical archetype</span><h3>{profile.archetype ?? "Balanced system"}</h3><p>{profile.archetype_reason ?? "Derived from possession, directness, width, and defensive height relative to its peers."}</p></div><div className="panel similar"><span className="eyebrow">Explained similarity</span><h2>Nearest styles</h2>{profile.similar.slice(0, 4).map((item, index) => <button key={`${item.team}-${index}`} onClick={() => { const match = profiles.find((candidate) => candidate.team === item.team); if (match) setSelected(match.id); }}><span>0{index + 1}</span><span className="similar-copy">{item.team}<small>{item.reasons?.join(" · ") ?? "Style match"}</small></span><strong>{Math.max(0, Math.round(item.similarity * 100))}%</strong></button>)}</div></section>{comparisonProfile && <ComparisonTable left={profile} right={comparisonProfile} />}</>}
    <section className="method" id="methodology"><span className="eyebrow">How to read it</span><h2>Not a prediction. A portrait of how a team plays.</h2><div><p><b>Possession & progression</b> measures pass length, forward intent, and circulation.</p><p><b>Territory</b> maps passes, carries, pressures, and recoveries across 30 pitch zones.</p><p><b>Style intelligence</b> explains similarity and uses peer-relative archetypes, not opaque labels.</p></div></section></>;
}
